version: "3"
services:

  mysql:
    container_name: mysql_spring
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: prueba
    ports:
      - '3380:3306'
    networks:
      - spring-mysql-network  
    volumes:
      - ../mysql:/var/lib/mysql
      - ./prueba.sql:/docker-entrypoint-initdb.d/prueba.sql
    restart: always

  tomcat:
    container_name: tomcat_spring
    image: tomcat:9.0
    ports:
      - 8080:8080
    networks:
      - spring-mysql-network
    depends_on:
      - mysql 
    volumes:
      - ../Docker/spring-boot-backend.war:/usr/local/tomcat/webapps/spring-boot-backend.war

networks:
    spring-mysql-network:
        driver: bridge
    
