version: "3"
services:

  mysql:
    container_name: mysql_spring
    image: mysql:5.7.41
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "mysql"
    ports:
      - "33306:3306"
    volumes:
      - ../mysql:/var/lib/mysql
    restart: always

  tomcat:
    container_name: tomcat_spring
    image: tomcat:9.0
    ports:
      - 8080:8080
    volumes:
      - ../Docker/spring-boot-backend.war:/usr/local/tomcat/webapps/spring-boot-backend.war
    links:
      - "mysql:mysql_spring"
