# Use root/mysql as user/password credentials

version: '3.8'

services:

  mysql:
    container_name: mysql_spring
    image: mysql:8.0
    command:
         --default-authentication-plugin=mysql_native_password
    environment:
       MYSQL_ROOT_PASSWORD: "mysql"
    ports:
      - "3306:3306"
    volumes:
      - ../mysql:/var/lib/mysql
    restart: on-failure
