version: "3"
services:

  tomcat:
    container_name: tomcat_spring
    image: tomcat:9.0
    ports:
      - 8080:8080
    volumes:
      - ../Docker/spring-boot-backend.war:/usr/local/tomcat/webapps/spring-boot-backend.war
